### ISSUE TITLE
tiny bug?

### ISSUE THREAD

**Issue by IulianD** [datashield/dsBaseClient#12]
Hello,

Very nice work, thanks.
This morning I noticed this warning when executing pretty much any client function:

~~~~
Warning message:
In if (cl1 == "list") { :
  the condition has length > 1 and only the first element will be used
~~~~

A bit of digging led me to this chunk of code in dsBaseClient:::getOpals:

~~~~
    for(i in 1:length(objs)){
      cl1 <- class(eval(parse(text=objs[i])))
       if(cl1 == 'list'){
......
~~~~

It looks like I have objects with more than one class in my environment.
Elsewhere you account for multiple classes (dsModellingClient:::getOpals):
~~~~
    for(i in 1:length(objs)){
      cl1 <- class(eval(parse(text=objs[i])))
       if(cl1[1] == 'list'){

  ..........
~~~~

Could you perhaps modify the first one one to match the second? You probably have your reasons to provide this function in all packages, however shouldn't the versions be identical?

Thanks.
Iulian

**Comment by andrewjamesturner0** [comment]
Good spot, thanks.

In fact, this was fixed in May 2015 (https://github.com/datashield/dsBaseClient/commit/31cb13f67a72a84c1271a53c6d51eb530ccfd14d). However this change has not been released yet.

Soon we will move to having all the client functions in one R package: [dsClient](https://github.com/datashield/dsClient). So in the future there will also only be one getOpals function.
