### ISSUE TITLE
dsDangerClient in tests

### ISSUE THREAD

**Issue by OllyButters** [datashield/dsBaseClient#141]
This shouldn't work - we don't install dsDangerClient in the CI. 

https://github.com/datashield/dsBaseClient/blob/9b9477d97804ff4113e767947411193251aeb5e9/tests/testthat/definition_tests/def-ds.dataFrameSort.R#L3

@StuartWheater & @LeireAbarrategui - could you have a look at this?

Thanks!

**Comment by StuartWheater** [comment]
Will do.

**Comment by LeireAbarrategui** [comment]
Hi,
I did the testing of ds.dataFrameSort function using the changes in the
server function that are here
https://github.com/StuartWheater/dsBase/blob/v6.0-dev_dataFrameSort/R/dataFrameSortDS.R
and the changes in client function
https://github.com/StuartWheater/dsBaseClient/blob/v6.0-dev/R/ds.dataFrameSort.R.
Because the functions that are in the branch v6.0-dev were not working
correctly.   So I think that this is the problem because these new changes
are not merged in the branch v6.6-dev.

Leire

**Comment by StuartWheater** [comment]
Hi, I was thing of replacing use of Danger function with calls to
ds.colnames, ds.class and ds.length to check to structure of the results.
Stuart

**Comment by StuartWheater** [comment]
Have been removed
