### ISSUE TITLE
quantiles in distributed datasets

### ISSUE THREAD

**Issue by tombisho** [datashield/dsBaseClient#25]
In one of our projects we have been asked about quantiles across all datasets. The ds.quantileMean code returns answers for combined quantiles, and looking at the code this is calculated by weighting by the size of study. This doesn't seem quite right to me, though I am happy to be proven wrong! I think it is not possible to calculate the quantiles for distributed data.

My suggested fix would be to allow calculation of quantiles per datasource only.

**Comment by davraam** [comment]
You are right Tom. Instead of allowing only calculation of quantiles per study, we can add a warning message informing the users about this behaviour. Paul has an idea for an algorithm that will be able to rank a variable across many datasources using encryption-decryption and this will allow us (in the future) to estimate correctly the combined quantiles.

**Comment by pb51** [comment]
Demetris is correct. We actually have a function now developed but we are going to have to implement it properly (Patricia is working on it). This function has to operate differently to most other DataSHIELD functions because it requires sequential encryption and decryption and this is the first function with this characteristic.
