### ISSUE TITLE
glmChecks() does not detect missing variables if specifying dataframe in formula due to incorrect test condition

### ISSUE THREAD

**Issue by tombisho** [datashield/dsBaseClient#61]
In glmChecks() on line 56 there is a test to see if a variable has been expressed in the format D$XXXX or XXXX:
````
        if(length(myterms) > 1){
````

myterms is either  a string XXXX or a vector of strings [D, XXXX]. If the condition above passes, then we test if the first item in the vector exists, which is the dataframe. The condition should be a test on equality with 1.

**Comment by pb51** [comment]
Never worked with glmChecks() before (and deliberately chose to suppress these checks by default). However, I've looked over the code and concur with what Tom has written.  Line 56 needs to be changed to: i

f(length(myterms) == 1){

Rather than me changing this and recommiting, please could I ask Stuart to make this small change?

**Comment by OllyButters** [comment]
Tagging @StuartWheater to action for v6.0 release.
